# Generated by Django 5.0.3 on 2024-04-04 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('pushups', models.PositiveIntegerField(default=0)),
                ('squats', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
