# Generated by Django 5.0.3 on 2024-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0002_delete_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='tours',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100000)),
            ],
        ),
    ]
