# Generated by Django 5.0.3 on 2024-04-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_alter_tours_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('duration', models.DurationField()),
                ('rating', models.FloatField()),
                ('promo', models.BooleanField(default=False)),
                ('transportation', models.PositiveSmallIntegerField(choices=[('1', 'Bus'), ('2', 'Train'), ('3', 'Plane')])),
                ('city', models.CharField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='tours',
        ),
    ]
