# Generated by Django 5.0.3 on 2024-04-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_tour_delete_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='accomodation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='cost_per_adult',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='cost_per_child',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='house_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='meal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='program_of_tour',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='typeofentertaiment',
            field=models.PositiveSmallIntegerField(choices=[('1', 'walking'), ('2', 'hiking'), ('3', 'excursion'), ('4', 'diving')], null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transportation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[('1', 'Bus'), ('2', 'Train'), ('3', 'Plane')]),
        ),
    ]
