# Generated by Django 5.0.3 on 2024-04-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_tour_accomodation_tour_cost_per_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='transportation_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transportation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Bus'), (2, 'Train'), (3, 'Plane')]),
        ),
        migrations.AlterField(
            model_name='tour',
            name='typeofentertaiment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'walking'), (2, 'hiking'), (3, 'excursion'), (4, 'diving')], null=True),
        ),
    ]
