# Generated by Django 5.0.3 on 2024-04-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_tour_transportation_bool_alter_tour_transportation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='typeofentertaiment',
            field=models.CharField(blank=True),
        ),
    ]
