# Generated by Django 5.0.3 on 2024-04-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_tour_typeofentertaiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='transportation',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane')]),
        ),
    ]
