# Generated by Django 5.0.3 on 2024-04-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_alter_tour_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='program_of_tour',
            field=models.CharField(blank=True, max_length=100000),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='transportation',
            field=models.CharField(blank=True, choices=[('bus', 'Bus'), ('train', 'Train'), ('plane', 'Plane')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tour',
            name='typeofentertaiment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
