# Generated by Django 5.0.3 on 2024-04-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_alter_tour_description_alter_tour_program_of_tour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='accomodation',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cost_per_adult',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='cost_per_child',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='program_of_tour',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='promo',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='region',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='street',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='transportation',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='transportation_bool',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='typeofentertaiment',
        ),
    ]
