# Generated by Django 5.0.3 on 2024-04-06 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_tour_destination_tour_durationnights_tour_objecttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), default=[''], size=8),
        ),
    ]
