# Generated by Django 5.0.3 on 2024-04-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_tour_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='iscanbuy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='price',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.CharField(default='Тур'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='destination',
            field=models.CharField(null=True),
        ),
    ]
