# Generated by Django 5.0.3 on 2024-04-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_tour_hasaudioguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
