# Generated by Django 5.0.3 on 2024-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_tour_russpassrecomendation_alter_tour_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='russpassRecomendation',
            field=models.BooleanField(default=False),
        ),
    ]
