# Generated by Django 5.0.3 on 2024-04-07 02:08

import django.contrib.postgres.fields
import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_hotel_review_tourist_alter_tour_themes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='review',
        ),
        migrations.AddField(
            model_name='hotel',
            name='distance_from_center',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=server.models.default_image, size=4),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ismeal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='isparking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='iswifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='popularity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='position',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.CharField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.SmallIntegerField(choices=[(5, '5 star'), (0, 'без звезд'), (2, '2 star'), (1, '1 star'), (4, '4 star'), (3, '3 star')], default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='typeofhotel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), default=server.models.default_image, size=4),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='themes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), default=server.models.default_theme, size=8),
        ),
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
